### PR TITLE
tracking nanoseconds actively sending/receiving over connection

### PR DESCRIPTION
**Pull request by joesis**
It extends the package to provide the same ability to https://github.com/getlantern/flashlight/pull/138, with a few differences:

1. The `NanosRead` and `NanosWrite` is the total time occupied by `Read()` and `Write()` method, respectively, which can be smaller than the period from the first `Read()` (or `Write()`) to the last one.
1. It reports periodically, not just when the connection is closed. It seems more useful as we can't predict how long the connection lasts.
1. To add `origin`, the caller can set it as the connection ID (by default it's remote address, which is same for each connection to specific proxy). We can also add a metadata field to `measured.Conn` if required.

Benchmark doesn't show significant performance degradation caused by this change. @oxtoacart how do you think about this method?

### CODE REVIEW

**Comment by oxtoacart** [comment]
> The NanosRead and NanosWrite is the total time occupied by Read() and Write() method, respectively, which can be smaller than the period from the first Read() (or Write()) to the last one.
It reports periodically, not just when the connection is closed. It seems more useful as we can't predict how long the connection lasts.

Interesting idea, but I don't know that this measures what we want, because Read and Write operate on OS buffers and can be very fast. Imagine a client that pauses between every call to Read() (i.e. a slow reader). If the client pauses long enough, each call to Read() could be very fast, so the overall throughput would seem very high, when in fact it could be much lower. Tracking the time from first read to last read isn't perfect either, but I think it provides a better approximation of the actual throughput. Maybe there's an even better way of measuring this?

> To add origin, the caller can set it as the connection ID (by default it's remote address, which is same for each connection to specific proxy). We can also add a metadata field to measured.Conn if required.

The metadata field would definitely be required. My change in https://github.com/getlantern/flashlight/pull/138 results in the entire ops context being included with our xfer measurement, including os information, proxy information, origin, etc. The easiest way to do this might be to just have measured use ops.Go or something like that. That way we don't need to create a new metadata abstraction for measured specifically.

**Comment by joesis** [comment]
> If the client pauses long enough, each call to Read() could be very fast, so the overall throughput would seem very high, when in fact it could be much lower.

Actually I'm worring about the opposite: Programs just block on `Read()` for tens of seconds waiting for data, until the server decides to send some. It should be very common in video streaming and WebSocket.

The normal throuput can be simply total bytes sent/recv divides the period, while the peak throughput determines how the proxy performs for the user. The absolute value maybe inaccurate, but the comparasion across proxies can be a good factor.

**Comment by myleshorton** [comment]
Should this one be closed guys or what's the current status @joesis and @oxtoacart?

**Comment by joesis** [comment]
Yeah definitely

**Pull request closed without merging**
